namespace: devopsarr
name: readarr
# Version will be updated by workflow
version: 0.0.1
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: "Ansible collection for Readarr"
license_file: LICENSE
tags:
  - readarr
  - arr
  - books
repository: https://github.com/devopsarr/ansible-collection-readarr
#documentation: https://github.com/ansible-collection-migration/devopsarr.readarr/tree/main/docs
homepage: https://github.com/devopsarr/ansible-collection-readarr
issues: https://github.com/devopsarr/ansible-collection-readarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml